# Generated by Django 3.2.9 on 2021-12-06 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=16, verbose_name='Course Code')),
                ('course_version', models.PositiveSmallIntegerField(default=None, null=True, verbose_name='Course Version')),
                ('course_name', models.CharField(max_length=50, verbose_name='Course Name')),
                ('course_required_credits', models.PositiveSmallIntegerField(verbose_name='Total Credits Requried to Complete this Course')),
                ('course_duration_limit', models.PositiveSmallIntegerField(default=8, verbose_name='Maximum Years to Complete this Course')),
                ('course_curate_electives_credits', models.PositiveSmallIntegerField(verbose_name='Specialized list of Electives required to complete this Course')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'ordering': ['faculty', 'course_code'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=64, unique=True, verbose_name='Faculty Name')),
            ],
            options={
                'verbose_name': 'faculty',
                'verbose_name_plural': 'faculties',
                'ordering': ['faculty_name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(max_length=32, verbose_name='Unit Code')),
                ('unit_name', models.CharField(max_length=128, verbose_name='Name of the Unit')),
                ('unit_credits', models.PositiveSmallIntegerField(verbose_name='Credits Awarded for Completing this Unit')),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.faculty', verbose_name='Faculty Responsible for the Unit')),
            ],
            options={
                'verbose_name': 'unit',
                'verbose_name_plural': 'units',
                'ordering': ['faculty', 'unit_code'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=128, verbose_name='Student ID')),
                ('student_name', models.CharField(max_length=256, verbose_name="Student's Name")),
                ('student_email', models.EmailField(max_length=128, verbose_name='Student Email')),
                ('student_intake_year', models.PositiveSmallIntegerField(verbose_name="Student's Intake Year")),
                ('student_intake_semester', models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'October Semester')], max_length=64, verbose_name="Student's First Semester Intake")),
                ('has_graduated', models.BooleanField(verbose_name='Have Student Graduated?')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.course', verbose_name='Course in which the Student is enrolled in')),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
                'ordering': ['course', 'student_id'],
            },
        ),
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolment_year', models.PositiveSmallIntegerField(verbose_name='Year in which Student is Taking this Unit')),
                ('enrolment_semester', models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'October Semester')], max_length=64, verbose_name='Semester in which Student is Taking this Unit')),
                ('enrolment_marks', models.SmallIntegerField(null=True, verbose_name='Marks obtained by the Student in this Unit')),
                ('has_passed', models.BooleanField(verbose_name='Has the Student Passed this Unit?')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student', verbose_name='Student Object in this Enrolment')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.unit', verbose_name='Unit in which the Student has Enrolled in')),
            ],
            options={
                'verbose_name': 'enrolment',
                'verbose_name_plural': 'enrolments',
                'ordering': ['student', 'unit'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.faculty', verbose_name='Faculty in which the Course belongs to'),
        ),
        migrations.CreateModel(
            name='CuratedElective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.unit')),
            ],
            options={
                'verbose_name': 'curated elective',
                'verbose_name_plural': 'curated electives',
                'ordering': ['course', 'unit'],
                'unique_together': {('course', 'unit')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_code', 'course_version')},
        ),
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.unit')),
            ],
            options={
                'verbose_name': 'core',
                'verbose_name_plural': 'cores',
                'ordering': ['course', 'unit'],
                'unique_together': {('course', 'unit')},
            },
        ),
    ]
