# Generated by Django 3.2.9 on 2021-12-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_course_required_credits_course_free_elective_credits'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=70)),
                ('file', models.FileField(upload_to='files')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
