# Generated by Django 3.2.9 on 2021-12-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_callistadatafile'),
    ]

    operations = [
        migrations.AddField(
            model_name='callistadatafile',
            name='name',
            field=models.CharField(default='abc', max_length=128, verbose_name='User-set Identifier for File'),
            preserve_default=False,
        ),
    ]
