# Generated by Django 3.2.9 on 2021-12-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_callistadatafile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callistadatafile',
            name='name',
            field=models.CharField(max_length=128, verbose_name='User Generated Identifier for File'),
        ),
        migrations.AlterField(
            model_name='callistadatafile',
            name='upload',
            field=models.FileField(upload_to='callista/', verbose_name='Student Callista Data'),
        ),
    ]
