# Generated by Django 3.2.9 on 2021-12-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_callistadatafile_has_been_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callistadatafile',
            name='has_been_processed',
            field=models.BooleanField(default=False, verbose_name='File has been processed into Database'),
        ),
    ]
