# Generated by Django 3.2.9 on 2021-12-12 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_callistadatafile_has_been_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=128, unique=True, verbose_name='Student ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_intake_semester',
            field=models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'October Semester')], max_length=64, null=True, verbose_name="Student's First Semester Intake"),
        ),
    ]
