# Generated by Django 3.2.9 on 2021-12-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_enrolment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=128, verbose_name='Student ID'),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('student_id', 'course')},
        ),
    ]
